# Generated by Django 5.1.2 on 2025-03-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doner/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipient/profile_pictures/'),
        ),
    ]
